### ISSUE TITLE
including this gem removes normal test visual feedback

### ISSUE THREAD

**Issue by josh-m-sharpe** [sporkrb/spork-testunit#28]
Visual feedback is no longer displayed after adding this gem to my bundle and running a test WITHOUT spork (ruby test/unit/user_test.rb):

.....F..E..etc...

This is useful information.  It lets me know the progress of the test and if it's hanging or not.

Despite spork being awesome, I still, occasionally want to run tests without it.  I don't think spork should interfere with that process, and I don't think I should have to comment out the gem line and bundle everytime I want to do so.

Thanks! :)

**Comment by nixme** [comment]
I'm not seeing the same behavior. Can you paste the acutual output you do see?

**Comment by matthuhiggins** [comment]
I believe this only happens on ruby 1.9.3

**Comment by josh-m-sharpe** [comment]
@matthuhiggins Negative, happens w/ 1.9.2.

**Comment by josh-m-sharpe** [comment]
@nixme here's some output with some test failures.

$ testdrb test/unit/user_test.rb 
Loaded suite UserTest
Started
E

Error:
test: deliver password reset instructions should change the perishable token. (UserTest):
RuntimeError: 
    test/unit/user_test.rb:149:in `block (2 levels) in class:UserTest'

E

Error:
test: deliver password reset instructions should send one email. (UserTest):
RuntimeError: 
    test/unit/user_test.rb:149:in `block (2 levels) in class:UserTest'

Finished in 6.318403 seconds.

#DRb::DRbUnknown:0x007fbfeb159bb0
0% passed

3.96 tests/s, 5.54 assertions/s

**Comment by forrest** [comment]
I'm experiencing the same problem with Ruby 1.9.2. I implemented the fix suggested on issue #2 (https://github.com/sporkrb/spork-testunit/issues/2). That got rid of the DRbUnknown error, but hasn't solved the 0% issue.

When running one of my tests, here is the output:

```
Finished in 3.681714 seconds.
16 tests, 222 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
0% passed
```

**Comment by aspiers** [comment]
I see this issue (the lack of visual progress feedback) both with _and_ without Spork. 

@forrest Which fix suggested in issue #2?  That issue was supposedly resolved in March 2011, way before your comment, although there are still problems unfortunately, which is why I'm interested in what you did - see issue #33 for details.

**Comment by forrest** [comment]
Sorry @aspiers. I ended up switching to rspec. Good luck.

**Comment by aspiers** [comment]
So did I :(
