### ISSUE TITLE
testdrb fails on Ruby 1.9.3

### ISSUE THREAD

**Issue by joliss** [sporkrb/spork-testunit#39]
Calling `testdrb` with or without arguments on Ruby 1.9.3-p0 fails with the following error message:

```
------------------------------
Error executing 
undefined method `setup_argv' for Test::Unit:Module
/home/ubuntu/.rbenv/versions/1.9.3-p0/lib/ruby/gems/1.9.1/gems/spork-testunit-0.0.7/lib/spork/test_framework/test_unit.rb:29:in `run_tests'
/home/ubuntu/.rbenv/versions/1.9.3-p0/lib/ruby/gems/1.9.1/gems/spork-0.9.0.rc9/lib/spork/run_strategy/forking.rb:13:in `block in run'
/home/ubuntu/.rbenv/versions/1.9.3-p0/lib/ruby/gems/1.9.1/gems/spork-0.9.0.rc9/lib/spork/forker.rb:21:in `block in initialize'
/home/ubuntu/.rbenv/versions/1.9.3-p0/lib/ruby/gems/1.9.1/gems/spork-0.9.0.rc9/lib/spork/forker.rb:18:in `fork'
/home/ubuntu/.rbenv/versions/1.9.3-p0/lib/ruby/gems/1.9.1/gems/spork-0.9.0.rc9/lib/spork/forker.rb:18:in `initialize'
/home/ubuntu/.rbenv/versions/1.9.3-p0/lib/ruby/gems/1.9.1/gems/spork-0.9.0.rc9/lib/spork/run_strategy/forking.rb:9:in `new'
/home/ubuntu/.rbenv/versions/1.9.3-p0/lib/ruby/gems/1.9.1/gems/spork-0.9.0.rc9/lib/spork/run_strategy/forking.rb:9:in `run'
/home/ubuntu/.rbenv/versions/1.9.3-p0/lib/ruby/gems/1.9.1/gems/spork-0.9.0.rc9/lib/spork/server.rb:48:in `run'
/home/ubuntu/.rbenv/versions/1.9.3-p0/lib/ruby/1.9.1/drb/drb.rb:1548:in `perform_without_block'
/home/ubuntu/.rbenv/versions/1.9.3-p0/lib/ruby/1.9.1/drb/drb.rb:1508:in `perform'
/home/ubuntu/.rbenv/versions/1.9.3-p0/lib/ruby/1.9.1/drb/drb.rb:1586:in `block (2 levels) in main_loop'
/home/ubuntu/.rbenv/versions/1.9.3-p0/lib/ruby/1.9.1/drb/drb.rb:1582:in `loop'
/home/ubuntu/.rbenv/versions/1.9.3-p0/lib/ruby/1.9.1/drb/drb.rb:1582:in `block in main_loop'
------------------------------
```

It's working fine on 1.9.2 for me.

**Comment by joliss** [comment]
Ah, it's a dup of #17 -- sorry about the noise.

@nixme, could you push out a new version, so 1.9.3 users can use a regular gem release instead of the git edge?
