### ISSUE TITLE
Exception raised when running Rails performance tests

### ISSUE THREAD

**Issue by alistairholt** [sporkrb/spork-testunit#45]
Hello,

Here's me setup:
- Ruby 1.9.2 p290
- rails 3.2.3
- spork 0.9.0
- spork-testunit 0.0.8

When Spork encounters a Rails performance test via the `testdrb` command I'm getting a `Exception encountered: #<SystemExit: exit>` message. Here's the backtrace:

```
/Users/alistair/.rvm/gems/ruby-1.9.2-p290/gems/activesupport-3.2.3/lib/active_support/testing/performance/ruby.rb:5:in `exit'
/Users/alistair/.rvm/gems/ruby-1.9.2-p290/gems/activesupport-3.2.3/lib/active_support/testing/performance/ruby.rb:5:in `rescue in <top (required)>'
/Users/alistair/.rvm/gems/ruby-1.9.2-p290/gems/activesupport-3.2.3/lib/active_support/testing/performance/ruby.rb:1:in `<top (required)>'
/Users/alistair/.rvm/gems/ruby-1.9.2-p290/gems/activesupport-3.2.3/lib/active_support/dependencies.rb:251:in `require'
/Users/alistair/.rvm/gems/ruby-1.9.2-p290/gems/activesupport-3.2.3/lib/active_support/dependencies.rb:251:in `block in require'
/Users/alistair/.rvm/gems/ruby-1.9.2-p290/gems/activesupport-3.2.3/lib/active_support/dependencies.rb:236:in `load_dependency'
/Users/alistair/.rvm/gems/ruby-1.9.2-p290/gems/activesupport-3.2.3/lib/active_support/dependencies.rb:251:in `require'
/Users/alistair/.rvm/gems/ruby-1.9.2-p290/gems/activesupport-3.2.3/lib/active_support/testing/performance.rb:311:in `<top (required)>'
/Users/alistair/.rvm/gems/ruby-1.9.2-p290/gems/activesupport-3.2.3/lib/active_support/dependencies.rb:251:in `require'
/Users/alistair/.rvm/gems/ruby-1.9.2-p290/gems/activesupport-3.2.3/lib/active_support/dependencies.rb:251:in `block in require'
/Users/alistair/.rvm/gems/ruby-1.9.2-p290/gems/activesupport-3.2.3/lib/active_support/dependencies.rb:236:in `load_dependency'
/Users/alistair/.rvm/gems/ruby-1.9.2-p290/gems/activesupport-3.2.3/lib/active_support/dependencies.rb:251:in `require'
/Users/alistair/.rvm/gems/ruby-1.9.2-p290/gems/actionpack-3.2.3/lib/action_dispatch/testing/performance_test.rb:1:in `<top (required)>'
/Users/alistair/Code/Ruby/xxxxxx/test/performance/browsing_test.rb:4:in `<top (required)>'
/Users/alistair/.rvm/gems/ruby-1.9.2-p290/gems/activesupport-3.2.3/lib/active_support/dependencies.rb:251:in `require'
/Users/alistair/.rvm/gems/ruby-1.9.2-p290/gems/activesupport-3.2.3/lib/active_support/dependencies.rb:251:in `block in require'
/Users/alistair/.rvm/gems/ruby-1.9.2-p290/gems/activesupport-3.2.3/lib/active_support/dependencies.rb:236:in `load_dependency'
/Users/alistair/.rvm/gems/ruby-1.9.2-p290/gems/activesupport-3.2.3/lib/active_support/dependencies.rb:251:in `require'
/Users/alistair/.rvm/gems/ruby-1.9.2-p290/gems/test-unit-2.4.8/lib/test/unit/collector/load.rb:105:in `block in collect_file'
/Users/alistair/.rvm/gems/ruby-1.9.2-p290/gems/test-unit-2.4.8/lib/test/unit/collector/load.rb:125:in `add_load_path'
/Users/alistair/.rvm/gems/ruby-1.9.2-p290/gems/test-unit-2.4.8/lib/test/unit/collector/load.rb:103:in `collect_file'
/Users/alistair/.rvm/gems/ruby-1.9.2-p290/gems/test-unit-2.4.8/lib/test/unit/collector/load.rb:40:in `block (2 levels) in collect'
/Users/alistair/.rvm/gems/ruby-1.9.2-p290/gems/test-unit-2.4.8/lib/test/unit/collector/load.rb:34:in `each'
/Users/alistair/.rvm/gems/ruby-1.9.2-p290/gems/test-unit-2.4.8/lib/test/unit/collector/load.rb:34:in `block in collect'
/Users/alistair/.rvm/gems/ruby-1.9.2-p290/gems/test-unit-2.4.8/lib/test/unit/collector/load.rb:125:in `add_load_path'
/Users/alistair/.rvm/gems/ruby-1.9.2-p290/gems/test-unit-2.4.8/lib/test/unit/collector/load.rb:30:in `collect'
/Users/alistair/.rvm/gems/ruby-1.9.2-p290/gems/test-unit-2.4.8/lib/test/unit/autorunner.rb:83:in `block in <class:AutoRunner>'
/Users/alistair/.rvm/gems/ruby-1.9.2-p290/gems/test-unit-2.4.8/lib/test/unit/autorunner.rb:360:in `[]'
/Users/alistair/.rvm/gems/ruby-1.9.2-p290/gems/test-unit-2.4.8/lib/test/unit/autorunner.rb:360:in `run'
/Users/alistair/.rvm/gems/ruby-1.9.2-p290/gems/spork-testunit-0.0.8/lib/spork/test_framework/test_unit.rb:88:in `run_tests'
/Users/alistair/.rvm/gems/ruby-1.9.2-p290/gems/spork-0.9.0/lib/spork/run_strategy/forking.rb:13:in `block in run'
/Users/alistair/.rvm/gems/ruby-1.9.2-p290/gems/spork-0.9.0/lib/spork/forker.rb:21:in `block in initialize'
/Users/alistair/.rvm/gems/ruby-1.9.2-p290/gems/spork-0.9.0/lib/spork/forker.rb:18:in `fork'
/Users/alistair/.rvm/gems/ruby-1.9.2-p290/gems/spork-0.9.0/lib/spork/forker.rb:18:in `initialize'
/Users/alistair/.rvm/gems/ruby-1.9.2-p290/gems/spork-0.9.0/lib/spork/run_strategy/forking.rb:9:in `new'
/Users/alistair/.rvm/gems/ruby-1.9.2-p290/gems/spork-0.9.0/lib/spork/run_strategy/forking.rb:9:in `run'
/Users/alistair/.rvm/gems/ruby-1.9.2-p290/gems/spork-0.9.0/lib/spork/server.rb:48:in `run'
/Users/alistair/.rvm/rubies/ruby-1.9.2-p290/lib/ruby/1.9.1/drb/drb.rb:1558:in `perform_without_block'
/Users/alistair/.rvm/rubies/ruby-1.9.2-p290/lib/ruby/1.9.1/drb/drb.rb:1518:in `perform'
/Users/alistair/.rvm/rubies/ruby-1.9.2-p290/lib/ruby/1.9.1/drb/drb.rb:1592:in `block (2 levels) in main_loop'
/Users/alistair/.rvm/rubies/ruby-1.9.2-p290/lib/ruby/1.9.1/drb/drb.rb:1588:in `loop'
/Users/alistair/.rvm/rubies/ruby-1.9.2-p290/lib/ruby/1.9.1/drb/drb.rb:1588:in `block in main_loop'
```

Any ideas?

Thanks

**Comment by bratsche** [comment]
@alistairholt Try adding this to your Gemfile

``` ruby
group :development, :test do  # Or wherever you've got spork-testunit pulled into
  gem 'ruby-prof'
end
```
