### ISSUE TITLE
Getting load error

### ISSUE THREAD

**Issue by sirupsen** [sporkrb/spork-testunit#5]
Using Spork from master:

$ bundle exec testdrb test/unit/blog_post_test.rb 
Exception encountered: #<LoadError: no such file to load -- test/unit/blog_post_test.rb>
backtrace:
/home/sirup/.rvm/gems/ruby-1.9.2-p0@aviastridchat/gems/activesupport-3.0.3/lib/active_support/dependencies.rb:239:in `require'
/home/sirup/.rvm/gems/ruby-1.9.2-p0@aviastridchat/gems/activesupport-3.0.3/lib/active_support/dependencies.rb:239:in`block in require'
/home/sirup/.rvm/gems/ruby-1.9.2-p0@aviastridchat/gems/activesupport-3.0.3/lib/active_support/dependencies.rb:227:in `load_dependency'
/home/sirup/.rvm/gems/ruby-1.9.2-p0@aviastridchat/gems/activesupport-3.0.3/lib/active_support/dependencies.rb:239:in`require'
/home/sirup/.rvm/gems/ruby-1.9.2-p0@aviastridchat/gems/test-unit-2.1.2/lib/test/unit/collector/load.rb:100:in `block in collect_file'
/home/sirup/.rvm/gems/ruby-1.9.2-p0@aviastridchat/gems/test-unit-2.1.2/lib/test/unit/collector/load.rb:117:in`add_load_path'
/home/sirup/.rvm/gems/ruby-1.9.2-p0@aviastridchat/gems/test-unit-2.1.2/lib/test/unit/collector/load.rb:99:in `collect_file'
/home/sirup/.rvm/gems/ruby-1.9.2-p0@aviastridchat/gems/test-unit-2.1.2/lib/test/unit/collector/load.rb:39:in`block (2 levels) in collect'
/home/sirup/.rvm/gems/ruby-1.9.2-p0@aviastridchat/gems/test-unit-2.1.2/lib/test/unit/collector/load.rb:33:in `each'
/home/sirup/.rvm/gems/ruby-1.9.2-p0@aviastridchat/gems/test-unit-2.1.2/lib/test/unit/collector/load.rb:33:in`block in collect'
/home/sirup/.rvm/gems/ruby-1.9.2-p0@aviastridchat/gems/test-unit-2.1.2/lib/test/unit/collector/load.rb:117:in `add_load_path'
/home/sirup/.rvm/gems/ruby-1.9.2-p0@aviastridchat/gems/test-unit-2.1.2/lib/test/unit/collector/load.rb:29:in`collect'
/home/sirup/.rvm/gems/ruby-1.9.2-p0@aviastridchat/gems/test-unit-2.1.2/lib/test/unit/autorunner.rb:83:in `block in <class:AutoRunner>'
/home/sirup/.rvm/gems/ruby-1.9.2-p0@aviastridchat/gems/test-unit-2.1.2/lib/test/unit/autorunner.rb:311:in`[]'
/home/sirup/.rvm/gems/ruby-1.9.2-p0@aviastridchat/gems/test-unit-2.1.2/lib/test/unit/autorunner.rb:311:in `run'
/home/sirup/.rvm/gems/ruby-1.9.2-p0@aviastridchat/gems/spork-testunit-0.0.4/lib/spork/test_framework/test_unit.rb:10:in`run_tests'
/home/sirup/.rvm/gems/ruby-1.9.2-p0@aviastridchat/bundler/gems/spork-0a437df35201/lib/spork/run_strategy/forking.rb:13:in `block in run'
/home/sirup/.rvm/gems/ruby-1.9.2-p0@aviastridchat/bundler/gems/spork-0a437df35201/lib/spork/forker.rb:21:in`block in initialize'
/home/sirup/.rvm/gems/ruby-1.9.2-p0@aviastridchat/bundler/gems/spork-0a437df35201/lib/spork/forker.rb:18:in `fork'
/home/sirup/.rvm/gems/ruby-1.9.2-p0@aviastridchat/bundler/gems/spork-0a437df35201/lib/spork/forker.rb:18:in`initialize'
/home/sirup/.rvm/gems/ruby-1.9.2-p0@aviastridchat/bundler/gems/spork-0a437df35201/lib/spork/run_strategy/forking.rb:9:in `new'
/home/sirup/.rvm/gems/ruby-1.9.2-p0@aviastridchat/bundler/gems/spork-0a437df35201/lib/spork/run_strategy/forking.rb:9:in`run'
/home/sirup/.rvm/gems/ruby-1.9.2-p0@aviastridchat/bundler/gems/spork-0a437df35201/lib/spork/server.rb:48:in `run'
/home/sirup/.rvm/rubies/ruby-1.9.2-p0/lib/ruby/1.9.1/drb/drb.rb:1558:in`perform_without_block'
/home/sirup/.rvm/rubies/ruby-1.9.2-p0/lib/ruby/1.9.1/drb/drb.rb:1518:in `perform'
/home/sirup/.rvm/rubies/ruby-1.9.2-p0/lib/ruby/1.9.1/drb/drb.rb:1592:in`block (2 levels) in main_loop'
/home/sirup/.rvm/rubies/ruby-1.9.2-p0/lib/ruby/1.9.1/drb/drb.rb:1588:in `loop'
/home/sirup/.rvm/rubies/ruby-1.9.2-p0/lib/ruby/1.9.1/drb/drb.rb:1588:in`block in main_loop'

**Comment by sirupsen** [comment]
Me being stupid and confused with 1.9.2 loading paths, `testdrb ./test/unit/blog_post_test.rb` works.
