### ISSUE TITLE
Wrong number of arguments exception

### ISSUE THREAD

**Issue by sirupsen** [sporkrb/spork-testunit#6]
Using Spork from master:

```
$ bundle exec testdrb ./test/unit/user_test.rb 

Error executing 
wrong number of arguments (3 for 2)
/home/sirup/.rvm/gems/ruby-1.9.2-p0@aviastridchat/gems/test-unit-            2.1.2/lib/test/unit/ui/console/testrunner.rb:29:in `initialize'
/home/sirup/.rvm/gems/ruby-1.9.2-p0@aviastridchat/gems/redgreen-1.2.2/lib/redgreen.rb:17:in `initialize'
/home/sirup/.rvm/gems/ruby-1.9.2-p0@aviastridchat/gems/test-unit-2.1.2/lib/test/unit/ui/testrunnerutilities.rb:24:in `new'
/home/sirup/.rvm/gems/ruby-1.9.2-p0@aviastridchat/gems/test-unit-2.1.2/lib/test/unit/ui/testrunnerutilities.rb:24:in `run'
/home/sirup/.rvm/gems/ruby-1.9.2-p0@aviastridchat/gems/test-unit-2.1.2/lib/test/unit/autorunner.rb:319:in `run'
/home/sirup/.rvm/gems/ruby-1.9.2-p0@aviastridchat/gems/spork-testunit-0.0.4/lib/spork/test_framework/test_unit.rb:10:in `run_tests'
/home/sirup/.rvm/gems/ruby-1.9.2-p0@aviastridchat/bundler/gems/spork-0a437df35201/lib/spork/run_strategy/forking.rb:13:in `block in run'
/home/sirup/.rvm/gems/ruby-1.9.2-p0@aviastridchat/bundler/gems/spork-0a437df35201/lib/spork/forker.rb:21:in `block in initialize'
/home/sirup/.rvm/gems/ruby-1.9.2-p0@aviastridchat/bundler/gems/spork-0a437df35201/lib/spork/forker.rb:18:in `fork'
/home/sirup/.rvm/gems/ruby-1.9.2-p0@aviastridchat/bundler/gems/spork-0a437df35201/lib/spork/forker.rb:18:in `initialize'
/home/sirup/.rvm/gems/ruby-1.9.2-p0@aviastridchat/bundler/gems/spork-0a437df35201/lib/spork/run_strategy/forking.rb:9:in `new'
/home/sirup/.rvm/gems/ruby-1.9.2-p0@aviastridchat/bundler/gems/spork-0a437df35201/lib/spork/run_strategy/forking.rb:9:in `run'
/home/sirup/.rvm/gems/ruby-1.9.2-p0@aviastridchat/bundler/gems/spork-0a437df35201/lib/spork/server.rb:48:in `run'
/home/sirup/.rvm/rubies/ruby-1.9.2-p0/lib/ruby/1.9.1/drb/drb.rb:1558:in `perform_without_block'
/home/sirup/.rvm/rubies/ruby-1.9.2-p0/lib/ruby/1.9.1/drb/drb.rb:1518:in `perform'
/home/sirup/.rvm/rubies/ruby-1.9.2-p0/lib/ruby/1.9.1/drb/drb.rb:1592:in `block (2 levels) in main_loop'
/home/sirup/.rvm/rubies/ruby-1.9.2-p0/lib/ruby/1.9.1/drb/drb.rb:1588:in `loop'
/home/sirup/.rvm/rubies/ruby-1.9.2-p0/lib/ruby/1.9.1/drb/drb.rb:1588:in `block in main_loop'
```

**Comment by timcharper** [comment]
Try with latest?
